# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'spring'
    organization: 'springbootvenkat'
    scannerMode: 'Other'
    #scannerMode: 'CLI'
    #configMode: 'file'
    #extraProperties: |
      # Additional properties that will be passed to the scanner, 
      # Put one key=value per line, example:
      # sonar.exclusions=**/*.bin
      #sonar.sources=src/**/*.*
      ##sonar.inclusions=$(Build.ArtifactStagingDirectory)/**/*.class
      ##sonar.inclusions=$(Build.ArtifactStagingDirectory)/**/*.java
      ##sonar.projectKey=com.example:venkatfirst
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    ##goals: 'package'
    goals: 'package -Dmaven.test.skip=true'
    sonarQubeRunAnalysis: true


- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'

- task: SSH@0
  inputs:
    sshEndpoint: 'venkateshkumar7.centralus.cloudapp.azure.com'
    runOptions: 'inline'
    inline: "/bin/kill $(ps -ef | grep 'venkatfirst-0.0.1-SNAPSHOT' | grep -v grep | awk '{print $2}')"
    readyTimeout: '20000'
#- task: SSH@0
  #inputs:
    #sshEndpoint: 'venkateshkumar7.centralus.cloudapp.azure.com'
    #runOptions: 'commands'
    #commands: 'ls -lrt;bash ./jar_folder/stopfirst.sh'
    #readyTimeout: '20000'
- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'venkateshkumar7.centralus.cloudapp.azure.com'
    sourceFolder: 'target'
    contents: '*.jar'
    targetFolder: '/home/venkateshkumard/jar_folder/'
    readyTimeout: '20000'

- task: SSH@0
  inputs:
    sshEndpoint: 'venkateshkumar7.centralus.cloudapp.azure.com'
    runOptions: 'commands'
    commands: 'bash ./jar_folder/startfirst.sh'
    readyTimeout: '20000'
- task: CopyFiles@2
  inputs:
    SourceFolder: 'target'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'


- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: '**/*.java'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'    
#- task: SonarCloudAnalyze@1

